server:
  port: 8080
spring:
  datasource:
    username: springbootpractice
    password: springbootpractice12
    url: jdbc:mysql://localhost:3306/department
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'

eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/